/**
 * Markdown receipt, suitable for a PR comment or an issue.
 * @param {import('./terminal.js').Report} report
 */
export function renderMarkdown(report) {
  const { high, medium, low } = report.counts;
  const out = [];
  out.push(`### sidetrace receipt`);
  out.push('');
  out.push(`\`${report.command.replace(/`/g, "'")}\` · exit ${report.exitCode ?? 'n/a'} · ${(report.durationMs / 1000).toFixed(1)}s`);
  out.push('');
  out.push(`**${high} high · ${medium} medium · ${low} low**`);
  out.push('');
  if (report.findings.length === 0) out.push('Nothing changed in the watched locations.');
  for (const f of report.findings) {
    out.push(`- **${f.severity.toUpperCase()}** \`${f.action}\` \`${f.title.replace(/`/g, "'")}\``);
    for (const n of f.notes) out.push(`  - ${n}`);
    if (f.lines && (f.lines.added.length || f.lines.removed.length)) {
      out.push('  ```diff');
      for (const l of f.lines.removed) out.push(`  - ${l}`);
      for (const l of f.lines.added) out.push(`  + ${l}`);
      out.push('  ```');
    }
  }
  out.push('');
  out.push('<sub>Generated by [sidetrace](https://github.com/Nithinfgs/sidetrace). Secrets are redacted. Not a sandbox.</sub>');
  return out.join('\n') + '\n';
}
